# Generated by Django 4.2.7 on 2023-11-26 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userInformatiom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=8)),
                ('genre', models.CharField(max_length=8)),
                ('countryTo', models.CharField(max_length=56)),
                ('durationPlaylist', models.CharField(max_length=5)),
            ],
        ),
    ]
