# Generated by Django 4.2.7 on 2023-12-01 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_userinformatiom_userinformation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformation',
            name='durationPlaylist',
            field=models.IntegerField(),
        ),
    ]
