# Generated by Django 4.2.7 on 2023-12-04 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_userinformation_durationplaylist'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinformation',
            name='countryFrom',
            field=models.CharField(default='', max_length=56),
        ),
    ]
